version: 0.0.1
achievements:
  - achievement:
      name: Bug Hunter
      icon: https://raw.githubusercontent.com/simonmazzaroth/example/main/.vaunt/Bug_Hunter.jpeg
      description: Thank you for finding a bug!   
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: labels in ['bug']
  - achievement:
      name: Exterminator
      icon: https://raw.githubusercontent.com/simonmazzaroth/example/main/.vaunt/Exterminator.jpeg
      description: Thank you for helping make Vaunt a bug free environment!   
      triggers:
        - trigger:
            actor: resolved_by
            action: issue
            condition: labels in ['bug'] & reason = COMPLETED
  - achievement:
      name: App Integrator
      icon: https://raw.githubusercontent.com/simonmazzaroth/example/main/.vaunt/App_Integrator.jpeg
      description: Thank you for making Vaunt more powerful!   
      triggers:
        - trigger:
            actor: resolved_by
            action: issue
            condition: labels in ['app-integration'] & reason = COMPLETED
  - achievement:
      name: AI Engine Expert
      icon: https://raw.githubusercontent.com/simonmazzaroth/example/main/.vaunt/AI_engine.jpeg
      description: Thank you for improving our AI Engine  
      triggers:
        - trigger:
            actor: resolved_by
            action: issue
            condition: labels in ['integration'] & reason = COMPLETED
  - achievement:
      name: Doc 
      icon: https://raw.githubusercontent.com/simonmazzaroth/example/main/.vaunt/Doc.jpeg
      description: Thank you for making Vaunt documentation better!   
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: merged = true & files in ['README.md', 'readme.md']
