version: 0.0.1
achievements:
  - achievement:
      name: Bug closer
      icon: https://raw.githubusercontent.com/simonmazzaroth/example/main/.vaunt/bug_closer.png
      description: Only closers get coffee!
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: closed = true
