version: 0.0.1
achievements:
  - achievement:
      name: Bug Hunter
      icon: icon_url
      description: Thank you for finding a bug!   
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: labels in ['bug']
  - achievement:
      name: Exterminator
      icon: icon_url
      description: Thank you for helping make MindsDB a bug free environment!   
      triggers:
        - trigger:
            actor: resolved_by
            action: issue
            condition: labels in ['bug'] & reason = COMPLETED
  - achievement:
      name: App Integrator
      icon: icon_url
      description: Thank you for making MindsDB more powerful!   
      triggers:
        - trigger:
            actor: resolved_by
            action: issue
            condition: labels in ['app-integration'] & reason = COMPLETED
  - achievement:
      name: AI Engine Expert
      icon: icon_url
      description: Thank you for improving our AI Engine  
      triggers:
        - trigger:
            actor: resolved_by
            action: issue
            condition: labels in ['integration'] & reason = COMPLETED
  - achievement:
      name: Doc 
      icon: icon_url
      description: Thank you for making MindsDB documentation better!   
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: merged = true & files in ['README.md', 'readme.md']
