version: 0.0.1
achievements:
  - achievement:
      name: Shooting Star
      icon: https://raw.githubusercontent.com/vauntdev/example/main/.vaunt/shooting_star.png
      description: Awarded for starring our repository, make a wish!
      triggers:
        - trigger:
            actor: author
            action: star
            condition: starred = true
  - achievement:
      name: Feedback
      icon: https://raw.githubusercontent.com/simonmazzaroth/DevRel_Uni/main/.vaunt/feedback.jpeg
      description: Thank you for your feedback
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: labels in ['Feedback']
            operator: "|"
  - achievement:
      name: Podcast Participatant!
      icon: https://raw.githubusercontent.com/simonmazzaroth/DevRel_Uni/main/.vaunt/podcast.jpeg
      description: Thank you for your participating! 
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: labels in ['Podcast']
            operator: "|"
  - achievement:
      name: Notetaker 
      icon: https://raw.githubusercontent.com/simonmazzaroth/DevRel_Uni/main/.vaunt/note taker.jpeg
      description: Thank you for your sharing your note! 
      triggers:
        - trigger:
            actor: author
            action: issue
            condition: labels in ['Notetaker']
            operator: "|"
